#lang racket
(require racket/trace)

(define (c n m)
  (if (or (= n 1) (= m 1) (= n m))
    1
    (+ (c (- n 1) m) (c (- n 1) (- m 1))))
  )
(display (c 1 1))
(newline)
(display (c 2 1))
(newline)
(display (c 2 2))
(newline)
(display (c 3 1))
(newline)
(display (c 3 2))
(newline)
(display (c 3 3))
(newline)
(display (c 4 1))
(newline)
(display (c 4 2))
(newline)
(display (c 4 3))
(newline)
(display (c 4 4))
