(define (sum-integers a b)
  (if (> a b)
      0
      (+ a (sum-integers (+ a 1) b)))
  )
(define (sum-cubes a b)
  (if (> a b)
      0
      (+ (cube a)
         (sum-cubes (+ a 1) b)
         ))
  )
(define (pi-sum a b)
  (if (> a b)
      0
      (+ (/ 1.0 (* a (+ a 2)))
         (pi-sum (+ a 4) b)
         )
      )
  )

(define (sum term a next b)
  (if (> a b)
      0
      (+ (term a)
         (sum term (next a) next b)
         ))
  )
(define (cube x) (* x x x))

(define (inc n) (+ n 1))
(define (sum-cubes a b)
  (sum cube a inc b)
  )

(define (identity x) x)
(define (sum-integers a b)
  (sum identity a inc b)
  )

(define (pi-sum a b)
  (define (pi-term x)
    (/ 1.0 (* x (+ x 2))))
  (define (pi-next x)
    (+ x 4))
1;51;5BB  (sum pi-term a pi-next b)
  )
(* 8 (pi-sum 1 1000))

(define (integral f a b dx)
  (define (add-dx x)
    (+ x dx)
    )
  (* (sum f (+ a (/ dx 2.0)) add-dx b) dx)
  )

(define (first-last f a b)
  (+ (f a) (f b))
  )

(define (even? n)
  (= (remainder n 2) 0)
  )

(define (h* a b n) (/ (- b a) n))
(define (simpsons-dame f a b n)
  (let ((h (h* a b n)))
  (define (add-1 a)
    (* (coeff a) (f (+ a h)))
    )
  ;;aを受け取り適切な係数を返す
  (define (coeff x)
    (cond
     ((= (- b x) n) 1)
     ((= (- b x) 0) 1)
     ((even? (- b x)) 4)
      (else 2)
     ))
   
  (* (sum f a add-1 b) h)
  ))

(define (simpsons f a b n)
  (define (add-2 n) (+ n 2))
   (let ((h (h* a b n)))
    (define (term n) (f (+ a (* n h))))
    (* (+
        (f a)
        (f b)
       (* 4 (sum term 1 add-2 n))
       (* 2 (sum term 2 add-2 (- n 1)))
       ) (/ h 3))
    )
   )
;;19:19->19:27
(define (simpsons2 f a b n)
  (let ((h (h* a b n)))
    (define (add1 n) (+ n 1))
    (define (y i) (f (+ a (* i h))))
    (define (coeff m)
      (cond
       ((= m n) (y m))
       ((= m 0) (y m))
       ((even? m) (* 4.0 (y m)))
        (else (* 2.0 (y m))
        )
       )
      )
    ( * (/ h 3.0) (sum coeff 0 add1 n))
    )
  )
    
(print (integral cube 0 1 0.01))
(print (integral cube 0 1 0.001))
(print (simpsons cube 0 1 100.0))
(print (simpsons cube 0 1 1000.0))
(print (simpsons2 cube 0 1 100.0))
(print (simpsons2 cube 0 1 1000.0))
