(define (cont-frac n d k)
  (define (iter i)
    (if (= i k)
        (/ (n i) (d i))
        (/ (n i) (+ (d i) (iter (+ i 1)))))
    )
  (iter 1)
  )

(define (cont-frac2 n d k)
  (define (iter i result)
    (if (= i 1)
        (/ (n i) (+ (d i) result))
        (iter (- i 1) (/ (n i) (+ (d i) result))))
    )
  (iter k 0)
  )

(define (tan-cx x k)
  (define (n i)
    (if (= i 1) x (* x x))
     )
  (define (d i)
    (- (* 2.0 i) 1)
    )
  (define (iter i)
    (if (= i k)
        (/ (n i) (d i))
        (/ (n i) (- (d i) (iter (+ i 1))))
        )
    )
  (iter 1)
  )
(print (tan-cx (/ 3.14 4) 1000))
(print (tan-cx (/ 3.14 3) 1000))
(print (tan-cx (/ 3.14 6) 1000))
