(define (>= a b)
   (or (> a b) (= a b))
  )
(define (square a)
    (* a a)
  )
(define (sum_square a b)
    (+ (square a)  (square b))
  )
(define (big_square a b c)
    (cond ((and (>= a c) (>= b c))
          (sum_square a b))
           ((and (>= a b) (>= c b))
          (sum_square a c))
           (else
               (sum_square b c)
             )
          )
  )
(print (big_square 1 2 3))
(print (big_square 1 3 2))
(print (big_square 2 1 3))
(print (big_square 2 3 1))
(print (big_square 3 1 2))
(print (big_square 3 2 1))