#lang debug racket
(require sicp)
(require racket/trace)
;20:16->20:39

(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      ("Insufficient funds")))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
      (else (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)
(define acc (make-account 100))
(display ((acc 'withdraw) 50))
(newline)
(display ((acc 'deposit) 5000))
(newline)
