#lang debug racket
(require sicp)
(require racket/trace)
;21:00->21:04
(define (make-account balance password-init)
  (define (withdraw password amount)
    (cond
        ((not (eq? password-init password)) "Incorrect password")
      ((>= balance amount)
           (begin (set! balance (- balance amount))
                  balance))
      (else ("Insufficient funds"))))
  (define (deposit password amount)
    (cond
      ((not (eq? password-init password)) "Incorrect password")
      (else (set! balance (+ balance amount))
            balance)))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
      (else (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)
(define acc (make-account 100 "aiueo"))
(display ((acc 'withdraw) "aiuoe" 50))
(newline)
(display ((acc 'withdraw) "aiueo" 50))
(newline)
(display ((acc 'deposit) "aiueo" 5000))
(newline)
(display ((acc 'deposit) "aiuow" 5000))
(newline)
