#lang debug racket
(require sicp)
(require racket/trace)
;多分25mぐらい
(define (rand-update x)
  (let ((a 27) (b 26) (m 127))
    (modulo (+ (* a x) b) m)))

(define (rand)
  (let ((x 7))
  (lambda (s)
            (cond
              ((eq? s 'reset)
               (lambda (value)
                       (begin (set! x (rand-update value)) x)))
               ((eq? s 'generate)
                (begin (set! x (rand-update x)) x))
               (else (error "Undefined message" s))
               )
            ))
  )
(define a (rand))
(display (a 'generate))
(newline)
(display (a 'generate))
(newline)
(display (a 'generate))
(newline)
(display "ここでリセット")
(newline)
(display ((a 'reset) 1))
(newline)
(display (a 'generate))
(newline)
(display (a 'generate))
(newline)
(display (a 'generate))
(newline)
(display "ここでリセット")
(newline)
(display ((a 'reset) 1))
(newline)
(display (a 'generate))
(newline)
(display (a 'generate))
(newline)
(display (a 'generate))
(newline)
