#lang debug racket
(require sicp)
(require racket/trace)
;21:45->21:50
;21:51->23:00
;出来た。
;孫も作れるので完璧。
(define (make-account balance password-init)
  (define (withdraw amount)
    (cond
      ((>= balance amount)
           (begin (set! balance (- balance amount))
                  balance))
      (else ("Insufficient funds"))))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (add-account password)
    (let ((my-password password))
      (define (dispatch m pass)
        (cond ((not (eq? pass my-password))
               (lambda (amount) "パスワードが違います"))
          ((eq? m 'add-account) add-account)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request: MAKE-ACCOUNT" m))))
      dispatch))
  (add-account password-init))
(define (make-joint acc password newpassword)
    ((acc 'add-account password) newpassword)
  )
(define acc (make-account 100 "aiueo"))
(display ((acc 'withdraw "aiuoe") 50))
(newline)
(display ((acc 'withdraw "aiueo") 50))
(newline)
(display ((acc 'deposit "aiueo") 5000))
(newline)
(display ((acc 'deposit "aiuow") 5000))
(define neko (make-joint acc "aiueo" "akstn"))
;(define neko ((acc 'add-account "aiueo") "akstn"))
(newline)
(display ((neko 'withdraw "akstn") 50))
(newline)
(display ((neko 'withdraw "aiueo") 50))
(newline)
(display ((neko 'deposit "aiueo") 5000))
(newline)
(display ((neko 'deposit "akstn") 5000))
(newline)
(display ((acc 'withdraw "aiuoe") 50))
(newline)
(display ((acc 'withdraw "aiueo") 50))
(newline)
(display ((acc 'deposit "aiueo") 5000))
(newline)
(display ((acc 'deposit "aiuow") 5000))
(define inu (make-joint neko "akstn" "111"))
(newline)(display "inu")(newline)
(display ((inu 'withdraw "111") 50))
(newline)
(display ((inu 'withdraw "aiueo") 50))
(newline)
(display ((inu 'deposit "aiueo") 5000))
(newline)
(display ((inu 'deposit "111") 5000))
(newline)(display "neko")(newline)
(display ((neko 'withdraw "akstn") 50))
(newline)
(display ((neko 'withdraw "aiueo") 50))
(newline)
(display ((neko 'deposit "111") 5000))
(newline)
(display ((neko 'deposit "akstn") 5000))
(newline)(display "acc")(newline)
(display ((acc 'withdraw "aiuoe") 50))
(newline)
(display ((acc 'withdraw "aiueo") 50))
(newline)
(display ((acc 'deposit "aiueo") 5000))
(newline)
(display ((acc 'deposit "111") 5000))
